default: version

version:
	@cargo -V

# sync deps
build:
	@cargo build

run:
	@cargo run --bin main

run-async:
	@cargo run --bin asyncmain

run-tokio:
	@cargo run --bin tokiomain

run-cache-server:
	@cargo run --bin cacheserver

run-cache-client:
	@cargo run --bin cacheclient

run-echo-server:
	@cargo run --bin echoserver
